name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        timeout: 60s
        command_timeout: 15m
        script: |
          echo "🚀 Starting deployment..."
          cd ~/school-of-options
          
          echo "📥 Pulling latest code..."
          git pull origin main
          
          echo "📦 Installing dependencies..."
          npm install --force
          
          echo "🏗️ Building application..."
          npm run build
          
          echo "♻️ Restarting application with PM2..."
          pm2 restart school-of-options || pm2 start npm --name "school-of-options" -- start
          pm2 save
          
          echo "✅ Deployment completed successfully!"
          pm2 status
